# Enable or disable default mode
sync = true

# Directory where configuration files and utxo DB are stored (default .gobalance)
workdir = "thatdir"

# Size of the in-memory utxo cache (in MB)
utxo_cache_size = 55555

# Number of blocks cached for recent transactions
recent_blocks = 22

# Number of cached addresses balance
balance_cache_size = 111111

[api]
# URL path for the api
url_prefix = "/api/v1/"

# Listen port
port = 1000

# bind to given ip address (empty string for all)
bind = "127.0.0.1" 

[bitcoind]
host = "localhost:8000"
user = "gobalance"
pass = "12345"
chain = "testnet99"
