# Enable or disable default mode
sync = true

# Peer mode of operation
mode = "seed"

# Directory where configuration files and utxo DB are stored (default .gobalance)
workdir = "thatdir"

# Size of the in-memory utxo cache
utxo_cache_size = 55555

# Number of blocks cached for recent transactions
recent_blocks = 22

# Number of cached addresses balance
balance_cache_size = 111111

[api]
# URL path for the api
url_prefix = "/api/v1/"

# Listen port
port = 1000

# bind to given ip address (empty string for all)
bind = "127.0.0.1" 

[peers]
port = 4000
seeds = ["seed1.unknown.com", "seed2.unknown.com",]
allow_local_ips = true
unreachable_marks = 10
unreachable_period = 100

[bitcoind]
hosts = ["localhost:8000", "localhost:9000"]
user = "gobalance"
pass = "12345"
chain = "testnet3"
